package:
  name: phantomjs
  version: 2.1.1

build:
   number: {{ environ.get('BINSTAR_BUILD', 1) }}

source:
  fn: phantomjs-2.1.1-linux-x86_64.tar.bz2 [linux64]
  url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 [linux64]
  sha256: 86dd9a4bf4aee45f1a84c9f61cf1947c1d6dce9b9e8d2a907105da7852460d2f [linux64]

  fn: phantomjs-2.1.1-macosx.zip  [osx]
  url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip [osx]
  sha256: 538cf488219ab27e309eafc629e2bcee9976990fe90b1ec334f541779150f8c1 [osx]

  fn: phantomjs-2.1.1-windows.zip [win64]
  url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip [win64]
  sha256: d9fb05623d6b26d3654d008eab3adafd1f6350433dfd16138c46161f42c7dcc8 [win64]

test:
  commands:
    - phantomjs -v

about:
  home: http://phantomjs.org/
